databases:
 - name: redash-db-next    
   plan: Standard
   postgresMajorVersion: 14
   databaseName: redash
   user: redash

services:
  - name: redash-web-next
    type: web
    autoDeploy: false    
    plan: Starter
    env: docker    
    dockerCommand: render-redash server
    healthCheckPath: /ping
    envVars:
      - fromGroup: redash
      - key: REDASH_DATABASE_URL
        fromDatabase:
          name: redash-db-next
          property: connectionString
      - key: REDASH_REDIS_URL
        fromService:
          name: redash-redis-next
          type: redis
          property: connectionString
      - key: PORT
        value: 5000
      - key: REDASH_WEB_WORKERS
        value: 1

  - name: redash-scheduler-next
    type: worker
    autoDeploy: false    
    plan: Starter
    env: docker    
    dockerCommand: render-redash scheduler
    envVars:
      - fromGroup: redash
      - key: REDASH_DATABASE_URL
        fromDatabase:
          name: redash-db-next
          property: connectionString
      - key: REDASH_REDIS_URL
        fromService:
          name: redash-redis-next
          type: redis
          property: connectionString
      - key: QUEUES
        value: "celery"
      - key: WORKERS_COUNT
        value: 1

  - name: redash-worker-scheduled-next
    type: worker
    autoDeploy: false    
    plan: Starter
    env: docker    
    dockerCommand: render-redash worker
    envVars:
      - fromGroup: redash
      - key: REDASH_DATABASE_URL
        fromDatabase:
          name: redash-db-next
          property: connectionString
      - key: REDASH_REDIS_URL
        fromService:
          name: redash-redis-next
          type: redis
          property: connectionString
      - key: QUEUES
        value: "scheduled_queries,schemas"
      - key: WORKERS_COUNT
        value: 1

  - name: redash-worker-adhoc-next
    type: worker
    autoDeploy: false    
    plan: Starter
    env: docker    
    dockerCommand: render-redash worker
    envVars:
      - fromGroup: redash
      - key: REDASH_DATABASE_URL
        fromDatabase:
          name: redash-db-next
          property: connectionString
      - key: REDASH_REDIS_URL
        fromService:
          name: redash-redis-next
          type: redis
          property: connectionString
      - key: QUEUES
        value: "queries,periodic,emails,default"
      - key: WORKERS_COUNT
        value: 1

  - name: redash-redis-next
    type: redis    
    plan: Standard
    maxmemoryPolicy: noeviction
    ipAllowList: []
    
envVarGroups:
  - name: redash
    envVars:
      - key: REDASH_LOG_LEVEL
        value: "INFO"
      - key: REDASH_COOKIE_SECRET
        generateValue: true
      - key: REDASH_SECRET_KEY
        generateValue: true
      - key: REDASH_FEATURE_ALLOW_CUSTOM_JS_VISUALIZATIONS
        value: true
      - key: REDASH_MAIL_SERVER
        value: smtp-relay.brevo.com
      - key: REDASH_MAIL_PORT
        value: 587
      - key: REDASH_MAIL_USE_TLS
        value: true
      - key: REDASH_MAIL_USERNAME
        sync: false 
      - key: REDASH_MAIL_PASSWORD
        sync: false 
      - key: REDASH_MAIL_DEFAULT_SENDER
        value: hello@geeksight.co
